### ISSUE TITLE
CLI add_image not working for 2D data

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#127]
Hi, 

when running `add_image` from CLI, the chunks parameter gets checked for 3D -> failure for 2D data.

```
... mobie/import_data/utils.py", line 156, in ensure_volume
    assert chunks[0] == 1, f"{chunks}"
           ^^^^^^^^^^^^^^
```

**Comment by martinschorb** [comment]
OK, 
found (and fixed) the reason.

Default file format in `add_image` is still `bdv.n5`. There is no such command line parameter, that's why it is chosen when running from CLI.

Three options exist to fix the problem:

- make `ome.zarr` the default for all `add_image`.
- implicitely select `ome.zarr` when calling `add_image` in the `main` function when run from CL
- add a CL parameter for file type

**Comment by constantinpape** [comment]
Is it now working after merging #128 @martinschorb ?

**Comment by constantinpape** [comment]
Can you check if this is working now @martinschorb ?

**Comment by martinschorb** [comment]
runs now.
