### ISSUE TITLE
best strategy for generating N5 from np array/memmap

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#24]
Hi,

what would be the best strategy of converting a numpy array/memmap into n5?

`make_bdv` is outdated, I guess...

**Comment by constantinpape** [comment]
> what would be the best strategy of converting a numpy array/memmap into n5?
> 
> `make_bdv` is outdated, I guess...

In memory data is currently not supported. So the best strategy is to use `make_bdv` to save an intermediate volume and then pass the corresponding filepath to the mobie utils function.

If you care about efficiency you can also try to write the file to the correct location already, i.e. `data/<DATASET_NAME>/images/local/<DATA_NAME>.n5`. The mobie function should then be clever enough to use the data that's already there and skip the volume copy. But I haven't really tried this yet, so some things might go wrong in practice.
