### ISSUE TITLE
creating multiple bookmarks/views

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#26]
Hi,

I found `add_dataset_bookmark` to be the function for adding v2 spec bookmarks, is that correct?
When I use it with `overwrite=False`, I assume this will add multiple bookmarks to one source.

my questions:

- How do I get things like `sourceNamesAfterTransform`, contrast limits or the whole `crop` functionality in there?
- Does it make sense to look at this functionality together/ split some work or should I try to generate the JSON some other way?

Thanks...

**Comment by constantinpape** [comment]
> I found `add_dataset_bookmark` to be the function for adding v2 spec bookmarks, is that correct?

Yes, that's correct. There's also two other function that are relevant:
- `add_additional_bookmark`, which will add a bookmark in an additional json (in `misc/bookmarks`)
- `add_grid_bookmark`, which is specifically for grid views

> When I use it with `overwrite=False`, I assume this will add multiple bookmarks to one source.

That's not quite correct. If `overwrite=True` and a bookmark with the name already exists it will be replaced. If `False`, existing bookmarks will not be replaced and the function will throw an error.
Once the bookmark exists you cannot update it with these functions, only fully replace it. For now, this would work by loading the dataset metadata and updating the corresponding dict in python:
```python
ds_meta = mobie.metadata.read_dataset_metadata(ds_folder)
view = ds_meta["views"][bookmark_name]  # this is the bookmark
view["sourceDisplays"][0]["imageDisplay"]["opacity"] = 0.5  # change something in the bookmark
# .... more changes
ds_metadata["views"][bookmark_name] = view
mobie.metadata.write_dataset_metadata(ds_folder, ds_meta) 
```
>     * How do I get things like `sourceNamesAfterTransform`, contrast limits or the whole `crop` functionality in there?

This can be done via the `display_settings` and `source_transforms` arguments. See [this example](https://github.com/mobie/mobie-utils-python/blob/spec-v-02/examples/project_creation_script.py#L169-L180). Though all of this needs to be documented better ...

**Comment by martinschorb** [comment]
Outdated with the `views` concept.
