### ISSUE TITLE
creating grid views

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-utils-python#29]
@martinschorb there is `get_grid_view` now, which you can use to create grid views for the gallery use case in the new tomo dataset.

The best example for this is currently the test: https://github.com/mobie/mobie-utils-python/blob/spec-v-02/test/metadata/test_view_metadata.py#L286-L315. The last of the tests `# additional transforms and changed source names` should correspond to your use-case with additional transformations and source names that are changed by the trafos.
For `transformed_sources` you will need to use the last name (after all prev transformations) for each source.

Let me know how it works and if you run into any issues.

**Comment by martinschorb** [comment]
Hi,
the grid generation works really nicely.
Can you check the "gallery" branch (currently checked out at `schwab/Tobias/MoBIE`? 
For me, the grid gets shown at z=1  every other time and hence outside the sources.
They all seem to start at `z=0`. Would it be possible to shift the sources in `z` to their respective centers?

That would especially be crucial for the crops.

**Comment by constantinpape** [comment]
> the grid generation works really nicely.

Awesome.

> For me, the grid gets shown at z=1 every other time and hence outside the sources.
> They all seem to start at `z=0`. Would it be possible to shift the sources in `z` to their respective centers?

This sounds rather like a problem with the viewer than with the spec/metadata. 
@tischi could you have a look?

**Comment by tischi** [comment]
@martinschorb 

I do not change the z-position of the sources when generating the grid view. 

Are you using the crop transform with `shiftToOrigin = true`; that would be the only place where we could see whether we can optimize something within the Java code. Otherwise, I think you should have a look in the JSON metadata.

**Comment by martinschorb** [comment]
No, so far these are the untransformed sources.

**Comment by martinschorb** [comment]
The viewer starts at the `z` position it was at before. Then it loads the grid view and then immediately jumps to `z=1.0`.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/35071867/127462485-30908fd8-0938-42d4-9fc7-5edb9d9b20d9.gif)

**Comment by tischi** [comment]
ok, so the issue is that the viewer jumps somewhere but the sources are at the correct position?

**Comment by martinschorb** [comment]
There is no positioning information in the grid view", these are the "pure" sources.

```JSON
"testgrid1": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "grid-view_images",
            "opacity": 1.0,
            "sources": [
              "CTRL_02_Grid3_c550",
              "B-ALL_00_Grid5_c0116",
              "B-ALL_00_Grid5_c0250"
            ]
          }
        },
        {
          "sourceAnnotationDisplay": {
            "lut": "glasbey",
            "name": "grid-view",
            "opacity": 0.5,
            "sources": {
              "0": [
                "CTRL_02_Grid3_c550"
              ],
              "1": [
                "B-ALL_00_Grid5_c0116"
              ],
              "2": [
                "B-ALL_00_Grid5_c0250"
              ]
            },
            "tableData": {
              "tsv": {
                "relativePath": "tables/grid-view"
              }
            },
            "tables": [
              "default.tsv"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "grid": {
            "sources": {
              "0": [
                "CTRL_02_Grid3_c550"
              ],
              "1": [
                "B-ALL_00_Grid5_c0116"
              ],
              "2": [
                "B-ALL_00_Grid5_c0250"
              ]
            }
          }
        }
      ],
      "uiSelectionGroup": "grid"
    }

**Comment by martinschorb** [comment]
The jump also happens in `x` and `y`, but these place the viewer in the correct position for the selected grid tile.

**Comment by tischi** [comment]
Are you at EMBL? I could pass by and you can show me.

**Comment by martinschorb** [comment]
Today @ home. Zoom now?

**Comment by tischi** [comment]
ok, can you send me a link by mail?

**Comment by constantinpape** [comment]
Hi both,
I couldn't follow any of this yesterday (my second does completely knocked me off my feet...) but as far as I understand https://github.com/mobie/mobie-viewer-fiji/issues/388 would solve this?!

**Comment by martinschorb** [comment]
> Hi both,
> I couldn't follow any of this yesterday (my second does completely knocked me off my feet...) but as far as I understand [mobie/mobie-viewer-fiji#388](https://github.com/mobie/mobie-viewer-fiji/issues/388) would solve this?!

Yes, this new issue was created as a result.

**Comment by constantinpape** [comment]
I am closing this issue for now to keep the discussions in the other one.
