### ISSUE TITLE
spec-v02: grid view probable inconsistency

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#32]
Hi,

I try to generate a grid:

```Python
view = mm.get_grid_view('data/tomo','grid1',[['SM_02_Grid2_c264','SM_02_Grid2_c222','SM_02_Grid2_c141','SM_01_Grid5_c166']])
```

If I don't provide the nested list, I get:

```

  File "/Users/schorb/code/mobie-utils-python/mobie/metadata/view_metadata.py", line 380, in get_grid_view
    assert isinstance(source_position, (list, tuple)), f"{type(source_position)}: {source_position}"

AssertionError: <class 'str'>: SM_02_Grid2_c264
```

However, with the nested list it results in a valid grid view:

```Python
{'isExclusive': True,
 'uiSelectionGroup': 'grid',
 'sourceDisplays': [{'imageDisplay': {'color': 'white',
    'contrastLimits': [0.0, 255.0],
    'name': 'grid1_images',
    'opacity': 1.0,
    'sources': ['SM_02_Grid2_c264',
     'SM_02_Grid2_c222',
     'SM_02_Grid2_c141',
     'SM_01_Grid5_c166']}},
  {'sourceAnnotationDisplay': {'opacity': 0.5,
    'lut': 'glasbey',
    'name': 'grid1',
    'sources': {0: ['SM_02_Grid2_c264',
      'SM_02_Grid2_c222',
      'SM_02_Grid2_c141',
      'SM_01_Grid5_c166']},
    'tableData': {'tsv': {'relativePath': 'tables/grid1'}},
    'tables': ['default.tsv']}}],
 'sourceTransforms': [{'grid': {'sources': ['SM_02_Grid2_c264'],
    'mergedGridSourceName': 'grid1-0'}},
  {'grid': {'sources': ['SM_02_Grid2_c222'],
    'mergedGridSourceName': 'grid1-1'}},
  {'grid': {'sources': ['SM_02_Grid2_c141'],
    'mergedGridSourceName': 'grid1-2'}},
  {'grid': {'sources': ['SM_01_Grid5_c166'],
    'mergedGridSourceName': 'grid1-3'}}]}
```

Now, when I try to add that view to the dataset:

```Python
mm.add_view_to_dataset('data/tomo','grid1',view)
```

```
Traceback (most recent call last):

  File "/Users/schorb/code/mobie-utils-python/mobie/validation/metadata.py", line 124, in validate_view_metadata
    validate_with_schema(view, "view")

  File "/Users/schorb/code/mobie-utils-python/mobie/validation/utils.py", line 54, in validate_with_schema
    jsonschema.validate(instance=metadata, schema=schema)

  File "/Users/schorb/miniconda3/envs/mobie/lib/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
    raise error

ValidationError: ['SM_02_Grid2_c264'] is not of type 'object'

Failed validating 'type' in schema[1]['properties']['grid']['properties']['sources']:
    {'additionalProperties': {'items': {'$ref': '#/definitions/name'},
                              'minItems': 1,
                              'type': 'array'},
     'type': 'object'}

On instance['grid']['sources']:
    ['SM_02_Grid2_c264']


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-14-14e38e5aebc9>", line 1, in <module>
    mm.add_view_to_dataset('data/tomo','grid1',view)

  File "/Users/schorb/code/mobie-utils-python/mobie/metadata/dataset_metadata.py", line 55, in add_view_to_dataset
    validate_view_metadata(view)

  File "/Users/schorb/code/mobie-utils-python/mobie/validation/metadata.py", line 127, in validate_view_metadata
    assert_true(False, msg)

  File "/Users/schorb/code/mobie-utils-python/mobie/validation/utils.py", line 64, in _assert_true
    raise ValueError(msg)

ValueError: ['SM_02_Grid2_c264'] is not of type 'object'

Failed validating 'type' in schema[1]['properties']['grid']['properties']['sources']:
    {'additionalProperties': {'items': {'$ref': '#/definitions/name'},
                              'minItems': 1,
                              'type': 'array'},
     'type': 'object'}

On instance['grid']['sources']:
    ['SM_02_Grid2_c264']
```

I would interpret it as the list being the problem...

**Comment by constantinpape** [comment]
The following runs through for me on the current main of the centrioles project:
```python
import mobie
view = mobie.metadata.get_grid_view('data/tomo','grid1',[['SM_02_Grid2_c264','SM_02_Grid2_c222','SM_02_Grid2_c141','SM_01_Grid5_c166']])
 mobie.validation.validate_view_metadata(view)
```

The most likely problem is that you have an old version of the schema cached. Can you run `rm ~/.mobie/*.json` (this will removed cached schema files) and try again?

**Comment by martinschorb** [comment]
Yes, that's it. It runs now.

However, when I try to open that grid in MoBIE I get:

```
Exception in thread "Thread-33" java.lang.IllegalArgumentException: Number of entities in cell too large. Use smaller cell size.
	at net.imglib2.img.cell.CellImgFactory.getCellDimensions(CellImgFactory.java:94)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.createCellGrid(ReadOnlyCachedCellImgFactory.java:158)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.createInternal(ReadOnlyCachedCellImgFactory.java:130)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.create(ReadOnlyCachedCellImgFactory.java:88)
	at de.embl.cba.mobie.transform.MergedGridSource.createMergedRandomAccessibleIntervals(MergedGridSource.java:89)
	at de.embl.cba.mobie.transform.MergedGridSource.<init>(MergedGridSource.java:57)
	at de.embl.cba.mobie.transform.GridSourceTransformer.createMergedSourceAndConverter(GridSourceTransformer.java:137)
	at de.embl.cba.mobie.transform.GridSourceTransformer.transform(GridSourceTransformer.java:40)
	at de.embl.cba.mobie.view.ViewManager.show(ViewManager.java:216)
	at de.embl.cba.mobie.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:457)
	at java.lang.Thread.run(Thread.java:748)
```
What could cause this? It is a 2x2 grid and as far as I can see in the view there is no other size specified explicitly.

**Comment by martinschorb** [comment]
the default table that `get_grid_view` produces looks wrong, it has only one entry:

```
annotation_id	source
0	SM_02_Grid2_c264-SM_02_Grid2_c222-SM_02_Grid2_c141-SM_01_Grid5_c166
```

**Comment by martinschorb** [comment]
When I manually change the table to have four entries, I still get the same error.

**Comment by martinschorb** [comment]
It's the `gallery` branch from here:
https://github.com/mobie/centrioles-tomo-datasets/

**Comment by tischi** [comment]
I am not sure if that's the view you are talking about but there are four grids with one source (probably wrong) instead of one grid with four sources (probably what you want): https://github.com/mobie/centrioles-tomo-datasets/blob/810911ed73f10a57666c8dbdbf42aa95b351743c/data/tomo/dataset.json#L11839

**Comment by tischi** [comment]
This is probably also wrong: https://github.com/mobie/centrioles-tomo-datasets/blob/810911ed73f10a57666c8dbdbf42aa95b351743c/data/tomo/dataset.json#L11821
It should be a map with four entries, something like `"0": source0, "1": source1, ...`

**Comment by martinschorb** [comment]
That's what I get from the `get_grid_view` function.

I now tried with these parameters passing individual sources lists as a list:
```Python
view=mm.get_grid_view('data/tomo','grid1',[['SM_02_Grid2_c264'],['SM_02_Grid2_c222'],['SM_02_Grid2_c141'],['SM_01_Grid5_c166']])
```

but it still gives the same error. (current commit)

**Comment by constantinpape** [comment]
> That's what I get from the `get_grid_view` function.
> 
> I now tried with these parameters passing individual sources lists as a list:
> 
> ```python
> view=mm.get_grid_view('data/tomo','grid1',[['SM_02_Grid2_c264'],['SM_02_Grid2_c222'],['SM_02_Grid2_c141'],['SM_01_Grid5_c166']])
> ```
> 
> but it still gives the same error. (current commit)

Ok, I need to double check this; this is either an issue in `get_grid_view` or in the way you call it (which means it's an issue in the function doc ;)). I have a meeting now, will have a look afterwards.

**Comment by martinschorb** [comment]
I tried manually assigning the grid's resulting source name from `mergedGridSourceName` to that view:

```
"sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "grid1_images",
            "opacity": 1.0,
            "sources": [
              "grid1-0"
            ]
```
That gave the exact same error.

**Comment by constantinpape** [comment]
@martinschorb There was an issue in how you call `get_grid_view`; each inner list needs to contain the sources for one grid position. See [this script](https://github.com/mobie/centrioles-tomo-datasets/blob/grid-test/add_grid_view.py) for how to use it correctly. I added a doc-string to `get_grid_view` and an assertion that it needs at least two grid positions, I hope that makes usage clearer.

@tischi opening the view still fails, although I think the metadata should be correct now.
It fails with 
```
Exception in thread "Thread-17" java.lang.IllegalArgumentException: Number of entities in cell too large. Use smaller cell size.
	at net.imglib2.img.cell.CellImgFactory.getCellDimensions(CellImgFactory.java:94)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.createCellGrid(ReadOnlyCachedCellImgFactory.java:158)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.createInternal(ReadOnlyCachedCellImgFactory.java:130)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.create(ReadOnlyCachedCellImgFactory.java:88)
	at de.embl.cba.mobie.transform.MergedGridSource.createMergedRandomAccessibleIntervals(MergedGridSource.java:89)
	at de.embl.cba.mobie.transform.MergedGridSource.<init>(MergedGridSource.java:57)
	at de.embl.cba.mobie.transform.GridSourceTransformer.createMergedSourceAndConverter(GridSourceTransformer.java:137)
	at de.embl.cba.mobie.transform.GridSourceTransformer.transform(GridSourceTransformer.java:40)
	at de.embl.cba.mobie.view.ViewManager.show(ViewManager.java:216)
	at de.embl.cba.mobie.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:457)
	at java.lang.Thread.run(Thread.java:748)
```
To reproduce:
- open `https://github.com/mobie/centrioles-tomo-datasets`, branch:  `grid-test`
- select `grid`->`grid1`

**Comment by tischi** [comment]
It turns out the individual images are too big [2432, 2432, 526] (java indexing issue) to put them into a single "cell" of a `ReadOnlyCachedCellImgFactory`.

Thus, for such data we currently would need to use the other grid transform (the non merged one). To test this, could you please add another view in the dataset.json that uses the `transformedGrid` instead of the `grid`?

**Comment by martinschorb** [comment]
I still get the same error, although I changed it...

```JSON
"sourceTransforms": [
        {
          "transformedGrid": {
            "mergedGridSourceName": "grid1-0",
            "sources": [
              "SM_02_Grid2_c264",
              "SM_02_Grid2_c222",
              "SM_02_Grid2_c141",
              "SM_01_Grid5_c166"
            ]
          }
        }
```

**Comment by constantinpape** [comment]
> I still get the same error, although I changed it...

@martinschorb simply changing the transformation name does not work, because `transformedGrid` has a different logic than `grid`. (That has historic reasons...). I reverted your commit.

@tischi I have added a new view called `trafo-grid` that uses the `transformedGrid` transform instead so you can test this.
(But I think in the long run this is not a good option because the transformedGrid is so slow. As a workaround, could you load the image on a lower resolution if the highest has flat index > max(int32)? (Java indexing is really broken ....))

**Comment by tischi** [comment]
> But I think in the long run this is not a good option 

I agree, I made an issue: https://github.com/mobie/mobie-viewer-fiji/issues/447

**Comment by tischi** [comment]
sorry it should be `transformedGrid` and not `transformGrid`; could you please change?

**Comment by constantinpape** [comment]
> sorry it should be `transformedGrid` and not `transformGrid`; could you please change?

It's called `transformGrid` in the spec: https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L481.
So I guess there the spec and code diverge?! I can change it, but note that it's also called `transformGrid` in https://github.com/mobie/covid-if-project, where we have tested all the grid views. (So I am unsure how that ever worked.)

**Comment by tischi** [comment]
I will change it in the Java code then!

**Comment by tischi** [comment]
The trafo-grid works 🥳 

You have to scroll a bit along the z-direction to see all sources because they have a different extend along the z-direction and the initial view is such that one only sees two of them.

We could try whether adding `centerAtOrigin = true` fixes this. 

<img width="602" alt="image" src="https://user-images.githubusercontent.com/2157566/133609617-ce060e58-c959-4cc1-96db-f40c2a94e8c7.png">

**Comment by martinschorb** [comment]
In the current Beta, I get:
```
java.lang.RuntimeException: Unknown class: transformGrid
```
in addition to the cell size error. So it's not fixed there yet, I suppose...

**Comment by tischi** [comment]
> So it's not fixed there yet, I suppose...

That is correct. I will upload the fix asap and then let you know.

**Comment by tischi** [comment]
@martinschorb I uploaded to the update site.

**Comment by martinschorb** [comment]
Confirm that the update worked, 
however with the dataset, I still get:

```
...
Caused by: java.lang.RuntimeException: Unknown class: transformGrid
...
```

**Comment by tischi** [comment]
I have trouble deploying this to Fiji at the moment......not sure what's going on. 
I will let you know.

**Comment by tischi** [comment]
@martinschorb I think I am making progress; it is working now?

**Comment by martinschorb** [comment]
confirm. It pulled 3 jars for the update.

the `trafo-grid` view works.

Will try with `centerAtOrigin = true`

**Comment by martinschorb** [comment]
`centerAtOrigin` works!

I will now try to set up the grids accordingly.

**Comment by martinschorb** [comment]
I guess this project leads to the need of discussing some general design concepts:

https://github.com/mobie/mobie-viewer-fiji/issues/450

Also, it seems that even when defining the `transormedSources` inside the grid definition it does not work as expected. (see the `centriole-grid` view, where I tried a grid of cropped regions)

**Comment by constantinpape** [comment]
> Also, it seems that even when defining the `transormedSources` inside the grid definition it does not work as expected. (see the `centriole-grid` view, where I tried a grid of cropped regions)

Can you please be more specific with the error descriptions. What exactly does not work? How did you generate the view?

**Comment by martinschorb** [comment]
> What exactly does not work? 

The grid tiles overlap. The additional transforms I introduced for the first entry (SM_02_Grid2_c264) do not get applied.

> How did you generate the view?

I manually copied the `sourceTransforms` from the individual crop view into the  `sourceTransforms` definition inside the grid view before the `transformGrid` and refer to the resulting local derived source.

**Comment by constantinpape** [comment]
Ok, I checked it and the `sourceTransformation` looks correct in principle, so I assume that this is a problem in the viewer.
One reason might be that only one of the sources is transformed, leading to very different sizes. So maybe transforming all sources would fix it.

@martinschorb you can also generate this view programatically (which should make it easier to add the source transforms). 
I will add example code for this later.

@tischi this is how it currently looks: (branch `grid-test`, view `centriole-grid`)
![Screenshot from 2021-09-16 18-54-10](https://user-images.githubusercontent.com/4263537/133653623-b742a488-fed3-4906-b392-3dd9c1428a01.png)

**Comment by martinschorb** [comment]
That's consistent with what I get. I had to rush for dinner with the kids, so didn't manage to take a screenshot. Thanks!

**Comment by tischi** [comment]
I think this one might be easy to explain: **The size of the grid currently is determined by the size of the first source in the list**. If that first one is smaller than the other sources, they will overlap.

We somewhere had an issue for dealing with "grids" of sources of different sizes in a sense that we would lay them out in some optimal tiling way, but I cannot find it right now.

I guess what I could try to see is whether we can change the viewer code such that the grid size is that of the largest source. Maybe that's better?

**Comment by martinschorb** [comment]
In addition to the overlap, when you disable all sources but the first (which is the one that should be transformed and cropped) you can see that neither the transform nor the cropping is performed by the viewer. If you check the individual centriole view (`SM_02_Grid2_c264_c1_crop`, second from the bottom) which has the identical transforms applied, it works there.

**Comment by constantinpape** [comment]
@martinschorb I updated the example script with a function that adds [a grid view with additional affine and crop transforms](https://github.com/mobie/centrioles-tomo-datasets/blob/grid-test/add_grid_view.py#L44). (Using the same parameters for each tomogram.)

The resulting view looks correct to me:
![Screenshot from 2021-09-16 20-18-27](https://user-images.githubusercontent.com/4263537/133665629-e9c59725-5c4f-4b7b-b1a3-0cf7625bb1e2.png)

I added another example that [additionaly uses `sourceNamesAfterTransform`](https://github.com/mobie/centrioles-tomo-datasets/blob/grid-test/add_grid_view.py#L85). Note that this is **not necessary for your use-case.** (It's only needed if you want to display the same source, under different transformations, multiple times in the same grid view).

This view looks incorrect (but again you don't need it and code and metadata are significantly easier without it):
![Screenshot from 2021-09-16 20-28-40](https://user-images.githubusercontent.com/4263537/133665639-6cac207f-9b30-48c1-9630-f8e1d2667c63.png)

@tischi I am pretty sure the metadata is correct for the above view, so there is probably still something going wrong in the viewer when using `sourcesAfterTransform`. In case you have time to debug tomorrow, this view is on branch `grid-test` with name `mock-crop-grid-trafo-names`.

**Comment by constantinpape** [comment]
> We somewhere had an issue for dealing with "grids" of sources of different sizes in a sense that we would lay them out in some optimal tiling way, but I cannot find it right now.

I can't find that issue right now either, but that's the clean solution in the long term and maybe something Ekaterina could work on
after some of her current projects.

> 
> I guess what I could try to see is whether we can change the viewer code such that the grid size is that of the largest source. Maybe that's better?

I think that would be a good intermediate solution.

**Comment by tischi** [comment]
> I guess what I could try to see is whether we can change the viewer code such that the grid size is that of the largest source. Maybe that's better?

@martinschorb would that work for you?

**Comment by martinschorb** [comment]
sounds feasible. Let's try.

**Comment by tischi** [comment]
I found one issue:

```
   "centriole-grid": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "trafo-grid_images",
            "opacity": 1.0,
            "sources": [
              "SM_02_Grid2_c264",
              "SM_02_Grid2_c222",
              "SM_02_Grid2_c141",
              "SM_01_Grid5_c166"
            ]
          }
        },
        {
          "sourceAnnotationDisplay": {
            "lut": "glasbey",
            "name": "trafo-grid",
            "opacity": 0.5,
            "sources": {
              "0": [
                "SM_02_Grid2_c264"
              ],
              "1": [
                "SM_02_Grid2_c222"
              ],
              "2": [
                "SM_02_Grid2_c141"
              ],
              "3": [
                "SM_01_Grid5_c166"
              ]
            },
            "tableData": {
              "tsv": {
                "relativePath": "tables/trafo-grid"
              }
            },
            "tables": [
              "default.tsv"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "affine": {
            "parameters": [
              0.9139845918849868,
              0.31631199291837175,
              -0.2541237669578392,
              0.0,
              -0.3163119929183716,
              0.947725139853161,
              0.04199740975719857,
              0.0,
              0.2541237669578391,
              0.04199740975719859,
              0.9662594520318256,
              0.0
            ],
            "sourceNamesAfterTransform": [
              "SM_02_Grid2_c264_c1_tfm"
            ],
            "sources": [
              "SM_02_Grid2_c264"
            ]
          }
        },
        {
          "crop": {
            "max": [
              2.3634952605030453,
              1.5452143159035596,
              1.2684008807526563
            ],
            "min": [
              1.3634952605030455,
              0.5452143159035596,
              0.26840088075265645
            ],
            "sourceNamesAfterTransform": [
              "SM_02_Grid2_c264_c1_crop"
            ],
            "sources": [
              "SM_02_Grid2_c264_c1_tfm"
            ]
          }
        },
        {
          "transformGrid": {
            "centerAtOrigin": true,
            "sources": {
              "0": [
                "SM_02_Grid2_c264_c1_crop"
              ],
              "1": [
                "SM_02_Grid2_c222"
              ],
              "2": [
                "SM_02_Grid2_c141"
              ],
              "3": [
                "SM_01_Grid5_c166"
              ]
            }
          }
        }
      ],
      "uiSelectionGroup": "grid"
```

In the `sourceAnnotationDisplay` you are currently not referring to the cropped source.

**Comment by tischi** [comment]
And I think there is another (understandable) misconception: neither the `sourceAnnotationDisplay` nor the `grid` transformation will actually show the sources!

The only thing that actually shows something is this: 

```
"sourceDisplays": [
        {
          "imageDisplay": { 
```

Thus, not to confuse yourself, I would always put this at the end of the view. 

So, to actually _view_ the cropped source you need to do:

```
"imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "trafo-grid_images",
            "opacity": 1.0,
            "sources": [
              "SM_02_Grid2_c264_c1_crop",
              "SM_02_Grid2_c222",
              "SM_02_Grid2_c141",
              "SM_01_Grid5_c166"
            ]
          }
```

So, the logic is, you can do all kind of stuff to sources: transform, crop, arrange in a grid, ...
But none of this will show them, you have to explicitly ask them to be shown 😸

**Comment by tischi** [comment]
I implemented code to use the largest rather than the first source for determining the grid size. When you fixed above issues in the JSON I can test it.

**Comment by constantinpape** [comment]
> In the `sourceAnnotationDisplay` you are currently not referring to the cropped source.

Ok, that makes sense. I know why this happens, I will fix it.

> So, the logic is, you can do all kind of stuff to sources: transform, crop, arrange in a grid, ...
> But none of this will show them, you have to explicitly ask them to be shown smile_cat

Yes, that's an issue in the python library; same reason the sources in annotationDisplays are wrong. I will fix it and update the view.

> Thus, not to confuse yourself, I would always put this at the end of the view.

I don't have control over this, everything is sorted by key (otherwise things get very confusing in the json).

**Comment by martinschorb** [comment]
OK,

I looked into it and wrote a function that takes the transforms from existing views and incorporates them into the grid view. It is based on `mock-crop-grid-trafo-names` because for some sources there are multiple transformed views of interest.

It runs nicely and gets validated but the grid view does not show up in MoBIE despite being present in the JSON.
What could cause this?
(branch `grid-test`)

**Comment by tischi** [comment]
> but "the grid view" does not show up

Would it be an idea to make it a habit to add a link to the starting line of the view in question in the current dataset.json? That would ensure that we can all efficiently check what could be going on.

**Comment by constantinpape** [comment]
@martinschorb I have fixed the issues with passing `source_names` in mobie-utils now and it works in the viewer as expected.
See `mock-crop-grid-trafo-names` on branch `grid-test2`. Note that I have changed the function signature; `grid_sources` is a nested list now in order to be consistent with `sources`, see https://github.com/mobie/centrioles-tomo-datasets/blob/grid-test2/add_grid_view.py#L130.

> > but "the grid view" does not show up
> 
> Would it be an idea to make it a habit to add a link to the starting line of the view in question in the current dataset.json? That would ensure that we can all efficiently check what could be going on.

In general yes. In this specific case the json is too large to be rendered by github so we can't send links to individual lines.

Anyway, I think that the problems in this issue are fixed now; gonna leave it open till @martinschorb had a chance to test it.

**Comment by tischi** [comment]
> I have fixed the issues with passing source_names in mobie-utils now and it works in the viewer as expected.

Thanks a lot!!

> In general yes. In this specific case the json is too large to be rendered by github so we can't send links to individual lines.

Good point. Maybe we could then just copy and paste the view into the issue.

**Comment by martinschorb** [comment]
> Good point. Maybe we could then just copy and paste the view into the issue.

Will do that in the future

**Comment by martinschorb** [comment]
WORKS!
