### ISSUE TITLE
convert from older MoBIE version

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#38]
Hi,

I have a big project that is done with an old MoBIE version.
It is in:

`/g/emcf/schorb/data/Irene_mobie/pag-dapex2-fibsem`

I modified the `projects.json` manually but then got stuck with the views.

I basically have a bunch of additional files describing bookmarks/views. They are in `../bookmarks...`
There is also a `bookmarks.json` where I concatenated them but then found out that they refer to different sources.

Could we look at it together at some point?

Thanks..!

**Comment by martinschorb** [comment]
I created the repo:
https://github.com/mobie/pag-dapex2-fibsem

and try to convert in the `convert` branch.

**Comment by constantinpape** [comment]
I see, this project is still in the very old MoBIE format ....
I will try to write a converter.

**Comment by martinschorb** [comment]
I guess the main need would be `bookmark -> view`. Then with these the datasets could be populated.

**Comment by constantinpape** [comment]
I have converted the project to spec v0.2 now, see https://github.com/mobie/pag-dapex2-fibsem/pull/1.
This should have also updated all the bookmarks.
Here's the script to do it (can also be done via CI: https://github.com/mobie/pag-dapex2-fibsem/blob/convert2/convert.py).

Note that I had to fix a few minor issues and this needs the latest `master` of mobie-utils-python to work.

**Comment by constantinpape** [comment]
p.s. I have checked that `validate_project` works for the converted project, but haven't checked if it can actually be opened by MoBIE. Let me know if you run into any issues with that/

**Comment by martinschorb** [comment]
I am checking right now.
Then I can add the remote sources and we should be good...

**Comment by martinschorb** [comment]
somehow only the first source is shown...

Also the "bookmark-views" are not recognized.

**Comment by martinschorb** [comment]
it looks like the reference to the n5 container is wrong.

There is a "Sample3.n5" but also a "Sample3_image.n5" as a duplicate. For all the others, there is only the "..._image.n5"

I will change the xmls accordingly.

**Comment by martinschorb** [comment]
Hmmm.

It looks like the n5 files are corrupted... BDV cannot open them and this is how they look in N5 viewer:
![Screenshot 2021-12-21 at 15 13 15](https://user-images.githubusercontent.com/35071867/146944245-5d883df1-d947-429a-ab1f-2b219bbd2655.png)

GDrive seems not to be a stable way of transferring such data...

**Comment by constantinpape** [comment]
That's unfortunate... I would recommend zipping everything and then checking integrity via checksums if you share the data via google drive or something similar.

**Comment by martinschorb** [comment]
> p.s. I have checked that `validate_project` works for the converted project, but haven't checked if it can actually be opened by MoBIE. Let me know if you run into any issues with that/

The datasets are wrong. The xml still resides in the ancient `"local"` directory.
In addition, I had to:
 for each dataset
- run `mm.create_dataset_structure(root,ds,['bdv-n5'])` for each dataset.
- move the xml (and n5) in there.
- modify the source entry

**Comment by constantinpape** [comment]
> The datasets are wrong. The xml still resides in the ancient `"local"` directory.

This is still ok. The location of the xml is defined in `imageData:bdv.n5:relativePath`. The path in there is then arbitrary. (But we enncourage to put it into `images/bdv-n5/...xml` as a convention to support adding different data file formats like bdv-n5-s3).

> * run `mm.create_dataset_structure(root,ds,['bdv-n5'])` for each dataset.
> * move the xml (and n5) in there.
> * modify the source entry

Ok, it's better if you update it so that we conform with the new convention. (But I didn't want to do it in my automatic updater because moving files in git can be a bit tricky automatically.)
