### ISSUE TITLE
input key for single files

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#50]
Hi,

I am trying to convert  a single `MRC` volume. What am I supposed to use as `input_key` for `add_image`?

 I tried `""` or `None` but get:

```
  File ".../cluster_tools/copy_volume/copy_volume.py", line 76, in run_impl
    ds = f[self.input_key]
  File ".../elf/io/mrc_wrapper.py", line 57, in __getitem__
    raise KeyError(f"Could not find key {key}")
KeyError: 'Could not find key '
```

**Comment by constantinpape** [comment]
Can you try `"data"`?

**Comment by martinschorb** [comment]
same error 😞

**Comment by martinschorb** [comment]
```Python
infile='/g/emcf/schorb/data/test.mrc'
outformat='ome.zarr'
chunks = list((64,128,128))
downscale_factors = list(([2,2,2],[2,2,2],[1,2,2],[1,2,2],[2,4,4],[2,2,2]))
resolution=[2,2,2]
outdir='./test'
mobie.add_image(infile,'data',outdir,'tomo','base',resolution,downscale_factors,chunks,file_format='ome.zarr')
```

**Comment by martinschorb** [comment]
OK, for whatever reason it seems to work now using `""`.
Thanks for your virtual aura!

**Comment by martinschorb** [comment]
but now, even the example failed when trying to run it again.

very strange. Let me investigate what's going on.

**Comment by martinschorb** [comment]
changing `[2,4,4]` to `[2,2,2]` makes it work again.

**Comment by martinschorb** [comment]
I have no idea what went wrong, but now it seems to run.

One more question: How can I efficiently parallelize across different volumes? I tried running `add_image` as a `multiprocessing.Pool` in parallel, but it seems that the `luigi` jobs from the different runs all seem to wait for each other before initiating a new submission cycle.

**Comment by martinschorb** [comment]
I think it works as intended. It just looks very synchronized because most of the input data has the same size and thus it takes almost exactly the same time to process one.

**Comment by constantinpape** [comment]
Just fyi, I also have another function for adding things in bulk: https://github.com/mobie/mobie-utils-python/blob/master/mobie/htm/data_import.py#L87.

But I have only used it for adding HTM data so far and it's not documented yet. The best example on how to use it is probably the test: https://github.com/mobie/mobie-utils-python/blob/master/test/htm/test_data_import.py#L108-L128

**Comment by constantinpape** [comment]
For your other issues: 
- the key for mrc should be `data`, see https://github.com/constantinpape/elf/blob/master/elf/io/mrc_wrapper.py#L42-L78
- I guess I have never tried downscaling with something like `list(([2,2,2],[2,2,2],[1,2,2],[1,2,2],[2,4,4],[2,2,2]))`, i.e. anisotropic scaling in higher scale levels. Is there a good reason why you need this? It would probably be not so hard to enable it.

**Comment by martinschorb** [comment]
Now I have some steady 100-200 conversion jobs running in parallel. That seems like a good scenario, not overloading the group share and getting reasonable prio while submitting.

Like that it's doing a bit more than 3 GB of raw volume data per minute.

**Comment by constantinpape** [comment]
> I will have a look. I was stumbling over this issue [numpy/numpy#9650](https://github.com/numpy/numpy/issues/9650) that the numpy RNG inside a multithreading pool has always the same value. Hence my nice randomly-timed submission was always synchronized.

yes, that's a well known issue in deep learning as well ;).




> Now I have some steady 100-200 conversion jobs running in parallel. That seems like a good scenario, not overloading the group share and getting reasonable prio while submitting.
> 
> Like that it's doing a bit more than 3 GB of raw volume data per minute.

Yes, that sounds reasonable!
