### ISSUE TITLE
default contrast limits with signed data types

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#53]
When adding an image, the view is created through

https://github.com/mobie/mobie-utils-python/blob/aa8ddda2b3ce43b0346810fdc4c6133fb7f1b13a/mobie/metadata/view_metadata.py#L339

which does not seem to pass any `displaysettings`  to `get_view` and finally `get_image_display`.

So it seems that independent of the input `dtype` the contrast limits will fall back to `[0,255]`.

https://github.com/mobie/mobie-utils-python/blob/aa8ddda2b3ce43b0346810fdc4c6133fb7f1b13a/mobie/metadata/view_metadata.py#L20

Ideally these would be set according to the image data type limits. This is especially crucial for signed types.

**Comment by constantinpape** [comment]
@martinschorb this is implemented now.
