### ISSUE TITLE
validation does not check for write access to folder

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#56]
Hi,

I am running into a (I admit, very unlikely) error using a CI run for tests:

https://github.com/mobie/mobie-utils-python/blob/8c51e92a79cff578f3fc75a11375092188cfee80/mobie/validation/utils.py#L20

wants to create `~/.mobie` without checking for access to that path. In my scenario, I run the tests as a temporary unprivileged user whose home directory does not exist.

**Comment by constantinpape** [comment]
I see. The usual solution to this is to add an env variable `MOBIE_FOLDER` or so which defaults to `~/.mobie`, but which you can over-write. Would this solve your problem? It's easy for me to implement.

**Comment by martinschorb** [comment]
I adjusted my CI workflow to provide the home directory. I just wasn't sure what would be a clean way of avoiding to run into this.
