### ISSUE TITLE
add me, please

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#7]
Hi @constantinpape ,

can I have access, so I can help improving doc etc.?

**Comment by constantinpape** [comment]
@martinschorb yes!
I will add you to the mobie-org later.

**Comment by constantinpape** [comment]
I invited you to mobie, once you accept you should have access to this repo :).
(Please wait a bit before doing anything on the docs though, I am currently moving around the docs between repos to reflect the recent changes we have made, will let you know when I am done with that.)
