### ISSUE TITLE
feature request: add existing table to segmentation

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-utils-python#74]
see also: https://github.com/mobie/mobie-viewer-fiji/issues/801

**Comment by constantinpape** [comment]
Implemented in #77 now; I will ping you when it's available on conda.

**Comment by constantinpape** [comment]
This is implement now; `add_segmentation` has the `init_table` parameter that can be used to pass the location of a pre-computed table file.
See https://github.com/mobie/mobie-utils-python/blob/master/mobie/segmentation.py#L22
