### ISSUE TITLE
update metadata not thread-safe

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#81]
Hi,

I am experiencing corrupted `dataset.json` files when writing metadata concurrently ( using `add_image` which makes sense to parallelize when converting image data).

The files always end up with extra
```
    }
  }
}
```

or sometimes 

```
ectionGroup": "images"
    }
  }
}
```
appended to the end of the file which is consistent with the correct (partial) last lines.

Everything else is OK and after removing the erroneous lines, the project validates correctly.

Is there a way to handle this rare but sometimes occurring case of concurrent access to the file?

**Comment by constantinpape** [comment]
This is a tricky issue to solve in general. I am just using `open(metadata_path, "a")` internally. So concurrent axis that hits this at the same time will result in undefined behavior / corrupted files.
Do you parallelize this in a ProcessPool / ThreadPool or via slum?
In the first case it could be solved by a `process.Lock / thread.Lock` around the metadata writing.
The second case is much more complicated; file locking on nfs is very complex and something I don't want to get into. So the best solution there is to do all the heavy lifting (converting the image data) in parallel and then write out the metadata sequentially afterwards. I have already implemented something like this for the case of HTM data: https://github.com/mobie/mobie-utils-python/blob/master/mobie/htm/data_import.py#L87-L112.
It might not quite fit your use-case, but should be relatively easy to adapt.

**Comment by martinschorb** [comment]
fixed with #123
