### ISSUE TITLE
add remote metadata does not verify server (protocol)

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#82]
Hi,

I noticed that the `metadata.add_remote...` calls do not verify that the address to the endpoint is valid.

I can put `s3.embl.de` and it will generate all metadata resulting in a valid project.
However, the `https://` prefix is missing and without it MoBIE does not open the data.

Does it make sense to check for a valid address when generating the metadata or when validating?

**Comment by constantinpape** [comment]
`add_remote` does not check if the path is valid, and it would require a few changes to implement it.
Instead you can use `validate_project` and pass `--require_remote_data 1` and it will check it.
See https://github.com/mobie/mobie-utils-python/blob/master/mobie/validation/project.py#L66-L69 for details on the command line flags.

**Comment by martinschorb** [comment]
`require_remote_data` does the job.
