### ISSUE TITLE
`validate_project` does not check project `ImageDataFormats`

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#83]
Hi,

I noticed that my project was validating correctly since both `dataset.json` and `project.json` are valid for themselves. However, the `ImageDataFormats` specified in the project do not match the source specs in the dataset and hence MoBIE does not open it failing with:

```
Source supports: ome.zarr
Source supports: ome.zarr.s3
Project settings support: bdv.n5
```

I would expect a check for this be part of the validation.

**Comment by constantinpape** [comment]
Good point. I will add it to the validation.

**Comment by constantinpape** [comment]
Done and available on master.
