### ISSUE TITLE
Support tables without bounding box columns

### ISSUE THREAD

**Issue by imagejan** [mobie/mobie-utils-python#97]
When adding a source segmentation including table data using (`add_source_to_dataset`), the table is required to have `bb_min_*` and `bb_max_*` columns, although their presence shouldn't be strictly required.

The column checking happens here:

https://github.com/mobie/mobie-utils-python/blob/d02ca5342accbb507edc9cd5abc3a90bd4120a84/mobie/tables/default_table.py#L17-L22

and in the validation code here:
https://github.com/mobie/mobie-utils-python/blob/0e2a5fd228b354e46440c415c5a3915df4ca5e3d/mobie/validation/tables.py#L74-L77

**Comment by constantinpape** [comment]
Good point! I am implementing less strict checks here: https://github.com/mobie/mobie-utils-python/pull/99

**Comment by constantinpape** [comment]
This is available on the current master branch now. @imagejan: Do you have an environment where you can test this from master?

**Comment by constantinpape** [comment]
> A flag to suppress the warnings (about missing "recommended" columns) would be great though, otherwise my output gets spammed when adding many tables. slightly_smiling_face

Ok, I'll look into it ;).

**Comment by constantinpape** [comment]
This will be included in the new release and I will close the issue. Feel free to reopen if anything is still missing or does not work as expected @imagejan.
